### ISSUE TITLE
Java naming conventions

### ISSUE THREAD

**Issue by MorrisLaw** [ddunig2/Translator#1]
"Class names should be nouns, in mixed case with the first letter of each internal word capitalized. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML)."

https://www.oracle.com/technetwork/java/codeconventions-135099.html

update the following files to be in line with Java naming convention:
-[translator.java](https://github.com/ddunig2/Translator/blob/master/Tranlator/src/Translate/translator.java)
-[logingui.java](https://github.com/ddunig2/Translator/blob/master/Tranlator/src/logingui.java)
-[mainScreen.java](https://github.com/ddunig2/Translator/blob/master/Tranlator/src/mainScreen.java)
-[myTranslator.java](https://github.com/ddunig2/Translator/blob/master/Tranlator/src/myTranslator.java)

**Comment by ddunig2** [comment]
Taken care of.
