### ISSUE TITLE
Remove commented out code

### ISSUE THREAD

**Issue by MorrisLaw** [ddunig2/Translator#3]
Shouldn't have commented out code in the codebase. Remove it if it isn't providing info needed to understand the program.
https://github.com/ddunig2/Translator/blob/master/Tranlator/src/Register.java#L11-L15
https://github.com/ddunig2/Translator/blob/master/Tranlator/src/mainScreen.java#L20
https://github.com/ddunig2/Translator/blob/master/Tranlator/src/mainScreen.java#L69
https://github.com/ddunig2/Translator/blob/master/Tranlator/src/mainScreen.java#L75
https://github.com/ddunig2/Translator/blob/master/Tranlator/src/mainScreen.java#L80
https://github.com/ddunig2/Translator/blob/master/Tranlator/src/mainScreen.java#L182
https://github.com/ddunig2/Translator/blob/master/Tranlator/src/mainScreen.java#L226
https://github.com/ddunig2/Translator/blob/master/Tranlator/src/logingui.java#L25

To the person reading the code, it is obvious what you are doing and these comments don't provide any extra useful information. So they're probably not needed:
https://github.com/ddunig2/Translator/blob/master/Tranlator/src/Translate/translator.java#L12
https://github.com/ddunig2/Translator/blob/master/Tranlator/src/Translate/translator.java#L14
https://github.com/ddunig2/Translator/blob/master/Tranlator/src/Translate/translator.java#L16

Maybe change this variable:
https://github.com/ddunig2/Translator/blob/master/Tranlator/src/Translate/translator.java#L17
To be:
`Translation russianTranslation`
This will remove the need to have the comment stating that it's a Russian translation.

**Comment by ddunig2** [comment]
Done.
